import { Link } from "react-router-dom";
import { ArrowUpRight, Check, Code2, ExternalLink, GitMerge, Layers3, MousePointer2, Pencil, Radio, ShieldCheck, Sparkles, WifiOff, Zap } from "lucide-react";
import ThemeToggle from "../components/ThemeToggle";
import Button from "../components/ui/Button";
import Badge from "../components/ui/Badge";

const steps = [["01", "Everyone draws", "Every shape, note, and cursor travels through the same room in real time.", Radio], ["02", "The network drops", "Local Yjs state keeps the work safe while offline.", WifiOff], ["03", "Work keeps moving", "Each person can keep sketching without waiting for a connection.", Pencil], ["04", "Changes merge", "CRDT state reconciles both histories automatically.", GitMerge]];
const capabilities = [["Presence", "See the room think", "Live cursors and collaborator status make a shared canvas feel shared.", MousePointer2], ["Offline-first", "Keep your flow", "Yjs keeps edits local and conflict-free when Wi-Fi disappears.", ShieldCheck], ["Permissioned rooms", "Share with intent", "Owner, editor, and viewer roles give every room the right openness.", Layers3]];
const Logo = () => <Link to="/" className="flex items-center gap-2.5 font-semibold tracking-tight"><span className="grid h-8 w-8 place-items-center rounded-xl bg-primary text-primary-foreground shadow-glow"><GitMerge className="h-4 w-4" /></span>Merge<span className="text-primary">Canvas</span></Link>;
const Presence = () => <div className="flex -space-x-2"><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-card bg-primary text-[10px] font-bold text-primary-foreground">A</span><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-card bg-accent text-[10px] font-bold text-primary-foreground">M</span><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-card bg-warning text-[10px] font-bold text-primary-foreground">J</span><span className="grid h-8 w-8 place-items-center rounded-full border-2 border-card bg-secondary text-[10px] font-semibold text-muted-foreground">+4</span></div>;

const LandingPage = () => {
  return <div className="min-h-screen overflow-x-hidden bg-background text-foreground">
    <header className="relative z-20 mx-auto flex max-w-7xl items-center justify-between px-5 py-5 sm:px-8"><Logo /><nav className="hidden gap-7 text-sm text-muted-foreground md:flex"><a href="#how-it-works" className="hover:text-foreground">How it works</a><a href="#capabilities" className="hover:text-foreground">Capabilities</a><a href="#stack" className="hover:text-foreground">Built with</a></nav><div className="flex items-center gap-2"><ThemeToggle /><Link to="/login" className="hidden px-3 py-2 text-sm text-muted-foreground hover:text-foreground sm:inline-flex">Sign in</Link><Button size="sm"><Link to="/signup">Start drawing</Link></Button></div></header>
    <main>
      <section data-hero className="relative mx-auto max-w-7xl px-5 pb-24 pt-16 sm:px-8 sm:pt-24 lg:pb-36"><div data-hero-parallax className="pointer-events-none absolute left-1/2 top-0 h-[38rem] w-[38rem] -translate-x-1/2 rounded-full bg-primary/15 blur-3xl" /><div data-hero-copy className="relative mx-auto max-w-4xl text-center"><Badge dot pulse variant="success" className="mb-7">Realtime canvas · offline by default</Badge><h1 className="text-balance text-5xl font-semibold tracking-[-.065em] sm:text-7xl lg:text-[6.5rem] lg:leading-[.92]"><span data-hero-word className="block">Ideas move</span><span data-hero-word className="block text-primary">when teams do.</span></h1><p className="mx-auto mt-8 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">A calm, collaborative whiteboard for teams that sketch, plan, and make decisions together — even when the connection does not cooperate.</p><div className="mt-9 flex flex-col items-center justify-center gap-3 sm:flex-row"><Button size="lg" rightIcon={<ArrowUpRight className="h-4 w-4" />}><Link to="/signup">Create a free room</Link></Button><a href="#how-it-works" className="inline-flex h-12 items-center gap-2 rounded-xl border border-border bg-card/60 px-5 text-sm font-medium hover:border-primary/40 hover:bg-accent">See how sync works <ArrowUpRight className="h-4 w-4" /></a></div></div>
        <div data-hero-canvas className="relative mx-auto mt-20 max-w-5xl"><div className="absolute -inset-5 rounded-[2rem] bg-primary/10 blur-2xl" /><div className="relative overflow-hidden rounded-3xl border border-border bg-card shadow-2xl"><div data-hero-chrome className="flex items-center justify-between border-b border-border px-4 py-3 text-xs text-muted-foreground sm:px-6"><span className="flex items-center gap-2"><span className="h-2 w-2 rounded-full bg-success" /> product-vision / spring</span><div className="flex items-center gap-4"><Presence /><span className="hidden sm:inline">7 people editing</span></div></div><div className="canvas-dot-grid relative h-[22rem] overflow-hidden sm:h-[30rem]"><svg viewBox="0 0 900 480" className="absolute inset-0 h-full w-full" fill="none" aria-label="Collaborative whiteboard preview"><path data-hero-stroke d="M110 160C180 75 250 250 350 150S520 80 610 175" stroke="hsl(var(--primary))" strokeWidth="4" strokeLinecap="round" /><path data-hero-stroke d="M480 335C545 245 650 360 770 235" stroke="hsl(var(--accent))" strokeWidth="4" strokeLinecap="round" /><rect data-hero-stroke x="130" y="280" width="180" height="105" rx="16" stroke="hsl(var(--foreground) / .35)" strokeWidth="2" /><circle data-hero-stroke cx="680" cy="145" r="66" stroke="hsl(var(--warning))" strokeWidth="3" /></svg><div className="absolute left-[20%] top-[28%] rounded-lg border border-primary/30 bg-card px-3 py-2 text-xs shadow-lg"><span className="text-primary">Ari</span> is exploring</div><div className="absolute bottom-[18%] right-[18%] rounded-lg border border-accent/30 bg-card px-3 py-2 text-xs shadow-lg"><span className="text-accent">Mina</span> added a note</div></div><div data-hero-chrome className="flex items-center justify-between border-t border-border bg-secondary/30 px-4 py-3 text-xs text-muted-foreground sm:px-6"><span className="flex items-center gap-2"><span className="h-1.5 w-1.5 rounded-full bg-success" /> All changes saved</span><span className="font-mono">YJS / CRDT SYNC</span></div></div></div>
      </section>
      <section className="border-y border-border bg-card/40"><div className="mx-auto grid max-w-5xl grid-cols-2 divide-x divide-border sm:grid-cols-4">{[["100", "%", "local edits persist"], ["0", "", "conflict dialogs"], ["3", "", "room roles"], ["1", "", "shared canvas"]].map(([num, suffix, label]) => <div key={label} className="px-5 py-7 text-center"><p data-stat data-stat-target={num} data-stat-suffix={suffix} className="text-3xl font-semibold">{num}{suffix}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>)}</div></section>
      <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-24 sm:px-8 lg:py-32"><div className="mb-14 max-w-xl"><p className="mb-3 font-mono text-xs uppercase tracking-[.2em] text-primary">The merge protocol</p><h2 className="text-4xl font-semibold tracking-[-.04em] sm:text-5xl">The room keeps its rhythm.</h2><p className="mt-5 leading-7 text-muted-foreground">MergeCanvas makes the hard parts of collaboration quiet and dependable.</p></div><div className="grid gap-4 md:grid-cols-2">{steps.map(([tag, title, body, Icon]) => <article key={tag} data-sync-step className="group rounded-2xl border border-border bg-card p-6 transition hover:-translate-y-1 hover:border-primary/40 hover:shadow-glow sm:p-8"><div className="flex justify-between"><span className="font-mono text-xs text-muted-foreground">{tag}</span><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary group-hover:bg-primary group-hover:text-primary-foreground"><Icon className="h-5 w-5" /></span></div><h3 className="mt-16 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{body}</p><div className="mt-7 h-1 w-12 rounded-full bg-primary/40" /></article>)}</div></section>
      <section id="capabilities" data-capabilities className="bg-secondary/40 px-5 py-24 sm:px-8 lg:py-32"><div className="mx-auto max-w-7xl"><p className="mb-3 font-mono text-xs uppercase tracking-[.2em] text-primary">Made for momentum</p><h2 className="text-4xl font-semibold tracking-[-.04em] sm:text-5xl">Less interface. More together.</h2><div className="mt-12 grid gap-4 lg:grid-cols-3">{capabilities.map(([label, title, body, Icon]) => <article key={label} data-capability className="rounded-2xl border border-border bg-card p-7"><Icon className="h-5 w-5 text-primary" /><p className="mt-10 font-mono text-xs uppercase tracking-widest text-muted-foreground">{label}</p><h3 className="mt-3 text-xl font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{body}</p><div className="mt-8 flex items-center gap-2 text-xs font-medium text-primary"><Check className="h-3.5 w-3.5" /> included in every room</div></article>)}</div></div></section>
      <section id="stack" data-tech-section className="mx-auto max-w-7xl px-5 py-24 sm:px-8"><div className="flex flex-col items-center text-center"><Sparkles className="h-5 w-5 text-primary" /><h2 className="mt-4 text-3xl font-semibold">Simple on the surface. Serious underneath.</h2></div><div className="mt-12 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{["React", "Canvas API", "Yjs", "Socket.io", "Node.js", "MongoDB"].map((item) => <div key={item} data-tech-card className="rounded-xl border border-border bg-card px-4 py-5 text-center text-sm font-medium hover:border-primary/40 hover:bg-accent">{item}</div>)}</div></section>
      <section data-cta className="mx-5 mb-8 rounded-3xl border border-primary/20 px-6 py-16 text-center sm:mx-8"><div data-cta-content><Zap className="mx-auto h-6 w-6 text-primary" /><h2 className="mt-5 text-4xl font-semibold">Give the next idea a room.</h2><Button size="lg" className="mt-8"><Link to="/signup">Start for free</Link></Button></div></section>
    </main><footer className="border-t border-border bg-card/30"><div className="mx-auto max-w-7xl px-5 py-10 sm:px-8"><div className="grid gap-10 md:grid-cols-[1.4fr_1fr_1fr_1.4fr]"><div><Logo /><p className="mt-4 max-w-xs text-sm leading-6 text-muted-foreground">A real-time whiteboard for ideas that need to move together.</p></div><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-foreground">Product</p><nav className="mt-4 grid gap-3 text-sm text-muted-foreground"><a href="#how-it-works" className="transition-colors hover:text-foreground">How it works</a><a href="#capabilities" className="transition-colors hover:text-foreground">Capabilities</a><a href="#stack" className="transition-colors hover:text-foreground">Technology</a></nav></div><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-foreground">Account</p><nav className="mt-4 grid gap-3 text-sm text-muted-foreground"><Link to="/login" className="transition-colors hover:text-foreground">Sign in</Link><Link to="/signup" className="transition-colors hover:text-foreground">Create an account</Link></nav></div><div className="rounded-2xl border border-border bg-background/60 p-5"><div className="flex items-center gap-2 text-sm font-medium"><Code2 className="h-4 w-4 text-primary" /> Open source project</div><p className="mt-2 text-sm leading-6 text-muted-foreground">Explore the code, follow development, or contribute on GitHub.</p><a href="https://github.com/Sumit-y88/Merge-canvas" target="_blank" rel="noreferrer" className="mt-4 inline-flex items-center gap-2 text-sm font-medium text-primary transition-colors hover:text-primary-hover">View repository <ExternalLink className="h-3.5 w-3.5" /></a></div></div><div className="mt-10 flex flex-col gap-3 border-t border-border pt-5 text-xs text-muted-foreground sm:flex-row sm:items-center sm:justify-between"><span>© {new Date().getFullYear()} MergeCanvas. Built for thoughtful collaboration.</span><span className="font-mono">React · Yjs · Socket.io</span></div></div></footer>
  </div>;
};
export default LandingPage;
